version: '3.8'
services:
  # nest-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-api
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - nest-postgres
  #   env_file:
  #     - .env
  #
  finance-db:
    image: postgres:14
    container_name: finance-db
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - finance-db:/var/lib/postgresql/data

volumes:
  finance-db:
    name: finance-db
